// This file is auto-generated by @hey-api/openapi-ts

export type ApiResponseDto = {
    /**
     * 正确码
     */
    code: number;
    /**
     * 请求是否成功
     */
    success: boolean;
    /**
     * 返回数据
     */
    data: {
        [key: string]: unknown;
    };
    /**
     * 错误描述
     */
    message: string;
};

/**
 * 交易类型
 */
export type TransactionType = 'income' | 'expenditure';

export type CategoryEntity = {
    /**
     * 分类ID
     */
    id: number;
    /**
     * 分类名称
     */
    name: string;
    /**
     * 交易类型
     */
    type: TransactionType;
    /**
     * 分类图标
     */
    icon: string;
    /**
     * 分类颜色
     */
    color: string;
    /**
     * 分类排序
     */
    sortOrder: number;
};

export type CreateTransactionDto = {
    /**
     * 金额
     */
    amount: number;
    /**
     * 交易类型
     */
    transactionType: string;
    /**
     * 交易日期
     */
    transactionDate: string;
    /**
     * 描述
     */
    description?: string;
    /**
     * 收款方式
     */
    payee?: string;
    /**
     * 分类id
     */
    categoryId?: number;
};

export type TransactionEntity = {
    /**
     * id
     */
    id: number;
    /**
     * 金额
     */
    amount: number;
    /**
     * 用户id
     */
    createUserId: string;
    /**
     * 交易类型
     */
    transactionType: 'income' | 'expenditure';
    /**
     * 交易日期
     */
    transactionDate: string;
    /**
     * 描述
     */
    description?: string;
    /**
     * 收款人
     */
    payee?: string;
    /**
     * 创建时间
     */
    createdAt: string;
    /**
     * 更新时间
     */
    updatedAt: string;
    /**
     * 分类id
     */
    categoryId: number;
    /**
     * 分类
     */
    category: CategoryEntity;
};

export type UpdateTransactionDto = {
    /**
     * 金额
     */
    amount?: number;
    /**
     * 交易类型
     */
    transactionType?: string;
    /**
     * 交易日期
     */
    transactionDate?: string;
    /**
     * 描述
     */
    description?: string;
    /**
     * 收款方式
     */
    payee?: string;
    /**
     * 分类id
     */
    categoryId?: number;
};

export type GenTransactionEntity = {
    /**
     * 金额
     */
    amount: number;
    /**
     * 交易类型
     */
    transactionType: 'income' | 'expenditure';
    /**
     * 交易日期
     */
    transactionDate: string;
    /**
     * 描述
     */
    description?: string;
    /**
     * 分类id
     */
    categoryId: number;
};

export type GenTransactionDto = {
    /**
     * 图片内容
     */
    message: string;
};

export type CategoryControllerFindAllData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/category';
};

export type CategoryControllerFindAllResponses = {
    default: ApiResponseDto & {
        data?: Array<CategoryEntity>;
    };
};

export type CategoryControllerFindAllResponse = CategoryControllerFindAllResponses[keyof CategoryControllerFindAllResponses];

export type TransactionControllerFindAllData = {
    body?: never;
    path?: never;
    query: {
        /**
         * 交易日期,时间戳
         */
        transactionDate: number;
    };
    url: '/api/transaction';
};

export type TransactionControllerFindAllResponses = {
    default: ApiResponseDto & {
        data?: Array<TransactionEntity>;
    };
};

export type TransactionControllerFindAllResponse = TransactionControllerFindAllResponses[keyof TransactionControllerFindAllResponses];

export type TransactionControllerCreateData = {
    body: CreateTransactionDto;
    path?: never;
    query?: never;
    url: '/api/transaction';
};

export type TransactionControllerCreateResponses = {
    default: ApiResponseDto & {
        data?: string;
    };
};

export type TransactionControllerCreateResponse = TransactionControllerCreateResponses[keyof TransactionControllerCreateResponses];

export type TransactionControllerRemoveData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/transaction/{id}';
};

export type TransactionControllerRemoveResponses = {
    default: ApiResponseDto & {
        data?: string;
    };
};

export type TransactionControllerRemoveResponse = TransactionControllerRemoveResponses[keyof TransactionControllerRemoveResponses];

export type TransactionControllerFindOneData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/transaction/{id}';
};

export type TransactionControllerFindOneResponses = {
    default: ApiResponseDto & {
        data?: TransactionEntity;
    };
};

export type TransactionControllerFindOneResponse = TransactionControllerFindOneResponses[keyof TransactionControllerFindOneResponses];

export type TransactionControllerUpdateData = {
    body: UpdateTransactionDto;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/transaction/{id}';
};

export type TransactionControllerUpdateResponses = {
    default: ApiResponseDto & {
        data?: string;
    };
};

export type TransactionControllerUpdateResponse = TransactionControllerUpdateResponses[keyof TransactionControllerUpdateResponses];

export type AiControllerGenTransactionData = {
    body: GenTransactionDto;
    path?: never;
    query?: never;
    url: '/api/ai/gen/transaction';
};

export type AiControllerGenTransactionResponses = {
    default: ApiResponseDto & {
        data?: GenTransactionEntity;
    };
};

export type AiControllerGenTransactionResponse = AiControllerGenTransactionResponses[keyof AiControllerGenTransactionResponses];

export type ClientOptions = {
    baseURL: string;
};