// This file is auto-generated by @hey-api/openapi-ts

export type Category = {
    type: 'income' | 'expenditure';
    id: number;
    name: string;
    icon: string;
    sortOrder: number;
};

export type TransactionCreateInput = {
    amount: string;
    transactionType: 'income' | 'expenditure';
    transactionDate: string | null;
    description: string | null;
    categoryId: number;
};

export type Transaction = {
    transactionType: 'income' | 'expenditure';
    id: number;
    amount: string;
    transactionDate: string | null;
    description: string | null;
    payee: string | null;
    createUserId: string;
    createdAt: string | null;
    updatedAt: string | null;
    categoryId: number;
    category: Category;
};

export type TransactionUpdateInput = {
    amount: string;
    transactionType: 'income' | 'expenditure';
    transactionDate: string | null;
    description: string | null;
    categoryId: number;
};

export type GetCategoryListData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/category';
};

export type GetCategoryListResponses = {
    /**
     * Returns a list of category
     */
    200: {
        ssuccess: boolean;
        data: Array<Category>;
    };
};

export type GetCategoryListResponse = GetCategoryListResponses[keyof GetCategoryListResponses];

export type GetTransactionListData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Transaction date
         */
        transactionDate: string;
    };
    url: '/api/transaction';
};

export type GetTransactionListResponses = {
    /**
     * Returns the transaction
     */
    200: {
        success: boolean;
        data: Array<Transaction>;
    };
};

export type GetTransactionListResponse = GetTransactionListResponses[keyof GetTransactionListResponses];

export type PostTransactionCreateData = {
    body?: TransactionCreateInput;
    path?: never;
    query?: never;
    url: '/api/transaction';
};

export type PostTransactionCreateResponses = {
    /**
     * Returns the created transaction
     */
    200: {
        success: boolean;
    };
};

export type PostTransactionCreateResponse = PostTransactionCreateResponses[keyof PostTransactionCreateResponses];

export type DeleteTransactionDeleteData = {
    body?: never;
    path: {
        /**
         * Transaction ID
         */
        transactionId: string;
    };
    query?: never;
    url: '/api/transaction/{transactionId}';
};

export type DeleteTransactionDeleteResponses = {
    /**
     * Returns if the transaction was deleted successfully
     */
    200: {
        success: boolean;
    };
};

export type DeleteTransactionDeleteResponse = DeleteTransactionDeleteResponses[keyof DeleteTransactionDeleteResponses];

export type GetTransactionFetchData = {
    body?: never;
    path: {
        /**
         * Transaction ID
         */
        transactionId: string;
    };
    query?: never;
    url: '/api/transaction/{transactionId}';
};

export type GetTransactionFetchResponses = {
    /**
     * Returns the transaction
     */
    200: {
        success: boolean;
    };
};

export type GetTransactionFetchResponse = GetTransactionFetchResponses[keyof GetTransactionFetchResponses];

export type PutTransactionUpdateData = {
    body?: TransactionUpdateInput;
    path: {
        /**
         * Transaction ID
         */
        transactionId: string;
    };
    query?: never;
    url: '/api/transaction/{transactionId}';
};

export type PutTransactionUpdateResponses = {
    /**
     * Returns the transaction
     */
    200: {
        success: boolean;
    };
};

export type PutTransactionUpdateResponse = PutTransactionUpdateResponses[keyof PutTransactionUpdateResponses];

export type ClientOptions = {
    baseURL: 'http://localhost:8787' | (string & {});
};