version: '3.8'
services:
  app:
    container_name: account-api
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./db:/app/prisma/db # 持久化 SQLite 数据库
      - ./logs:/app/logs # 可选：日志持久化
    environment:
      PORT: 3000
      TZ: Asia/Shanghai
